# shiny-server.conf
run_as shiny;

server {
  listen 3838;

  # Serve tutorials folder as a website of tutorials
  location /FOS {
    site_dir /srv/FOS;
    log_dir /var/log/shiny-server;
    directory_index on;
  }
}

